### ISSUE TITLE
arXiv entries

### ISSUE THREAD

**Issue by astoff** [pzorin/bibretrieve#8] opened 2017-09-06 12:00 UTC
The line https://github.com/pzorin/bibretrieve/blob/6aea308680f8f2cab4c5ae06bb3b64bd0a2d9215/bibretrieve-base.el#L156 
should be `(replace-match (concat "@misc{arxiv:" arxivid ",") nil)))`, otherwise some labels become all-caps.

Also, modifying the title field delimiters from `"{` ... `}"` is a bad idea, because in this case bibtex downcases the title, with unreliable results.

**Comment by pzorin** [comment] 2017-09-06 17:42
Thanks for pointing out the optional argument of `replace-match`, fixed in a4217d7.
Bibtex behaved the way it does by design. I am more annoyed by unnecessary capitalization that some authors use than by occasionally having to fix proper names.

**Closed by pzorin** 2017-09-06 17:42 UTC

**Comment by pzorin** [comment] 2018-02-04 12:02
A note on superfluous curly braces: if the author or title field starts with a curly brace, it does not get sorted properly by `biber` (or at least it did not for some previous version). Since arxiv.org now uses texlive 2016, I have started using `biblatex` and `biber` for all my submissions. Therefore I do not support `bibtex` (the program) any more.
